ARG NODE_VERSION=latest
FROM node:${NODE_VERSION}-slim

RUN apt-get -y update && apt-get -y install curl git jq
# dependencies just used for @pact-foundation/pact testing
# so you don't need to use those in your own projects

ENTRYPOINT [ "bash", "-c", "scripts/ci/build-and-test.sh" ]