# Serverless SNS
service: pact-events

provider:
  name: aws
  runtime: nodejs12.x
  iamRoleStatements:
    - Effect: "Allow"
      Resource: "*"
      Action:
        - "sns:*"
  environment:
    TOPIC_ARN: { "Fn::Join":  ["", ["arn:aws:sns:us-east-1:", { "Ref": "AWS::AccountId" }, ":pact-events"] ] }

package:
  individually: true
  exclude:
    - node_modules/**

functions:
  provider:
    handler: provider/index.handler
  consumer:
    handler: consumer/index.handler
    events:
      - sns: pact-events
