name: SmartBear Supported Issue Label Added

on:
  issues:
    types:
      - labeled

jobs:
  call-workflow:
    uses: pact-foundation/.github/.github/workflows/smartbear-issue-label-added.yml@1633eb6f257f636b4c81a1a2a49de662f4ad96d5 # master
    secrets: inherit
