name: SmartBear Supported Issue Label Added

on:
  issues:
    types:
      - labeled

jobs:
  call-workflow:
    uses: pact-foundation/.github/.github/workflows/smartbear-issue-label-added.yml@f8fd527b1d6ff4bbf48597ef88e32772f72c644b # master
    secrets: inherit
