name: SmartBear Supported Issue Label Added

on:
  issues:
    types:
      - labeled

jobs:
  call-workflow:
    uses: pact-foundation/.github/.github/workflows/smartbear-issue-label-added.yml@95185f4fc661406e8817f6ba0bc81ac3e8e94231 # master
    secrets: inherit
