name: Triage Issue

on:
  issues:
    types:
      - opened
      - labeled
  pull_request:
    types:
      - labeled

jobs:
  call-workflow:
    uses: pact-foundation/.github/.github/workflows/triage.yml@3a9ea59381bc45df621f1f97f5878a6b2f066110 # master
    secrets: inherit
